### ISSUE TITLE
JRawValue should use the registered serializer

### ISSUE THREAD

**Issue by BrannonKing** [SignalR/SignalR#3304]
It took me a while to figure out why my $type data was not being used when deserializing method parameters on the server. I knew that I had correctly registered the JsonSerializer with the right settings. After digging through the source, and writing a custom parameter resolver, I got it figured out. The JRawValue class creates a new instance of the serializer rather than getting the one registered in the global DependencyResolver. It should use the registered serializer instead. I had to write this code (below) to work around the issue. I'm quite disturbed at having to use reflection to get the actual JSON string out.

My server configuration contains this:

``` csharp
var settings = SerializationHelper.Settings; // including TypeNameHandling.Auto
var serializer = JsonSerializer.Create(settings);
GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => serializer);
var resolver = new Resolver(serializer);
GlobalHost.DependencyResolver.Register(typeof(IParameterResolver), () => resolver);
```

and here is the resolver:

``` csharp
private class Resolver : DefaultParameterResolver
{
    private readonly JsonSerializer _serializer;

    public Resolver(JsonSerializer serializer)
    {
        _serializer = serializer;
    }

    private FieldInfo _valueField;
    public override object ResolveParameter(ParameterDescriptor descriptor, Microsoft.AspNet.SignalR.Json.IJsonValue value)
    {
        if (value.GetType() == descriptor.ParameterType)
        {
            return value;
        }

        if (_valueField == null)
            _valueField = value.GetType().GetField("_value", BindingFlags.Instance | BindingFlags.NonPublic);

        var json = (string)_valueField.GetValue(value);
        using (var reader = new StringReader(json))
            return _serializer.Deserialize(reader, descriptor.ParameterType);
    }
}
```

**Comment by MrKWatkins** [comment]
Also causing me issues. I have a hub method that takes an object for its parameters. One of the properties on that object requires a custom JsonConverter to (de)serialize. Due to this bug the registered serializer with my custom JsonConverter isn't being used so deserialization from JSON fails.

My registered serializer also has a custom trace writer that logs (de)serialization exceptions. I need this to log serialization errors from the result of a hub method - these exceptions seem to miss my custom HubPipelineModule with OnIncomingError override. As JRawValue isn't using my registered serializer I had no errors logged at all for this exception and only managed to work it out by attaching a debugger with break on all exceptions...

**Comment by DaveOMac** [comment]
Coming from http://stackoverflow.com/a/27004828 this issue is important to me.

We have a hub method that takes an abstract type "Slide" as a parameter which has several derived implementations "ImageSlide", "VideoSlide", etc, etc.

We've used this setup in other "Newtonsoft JSON" environments (WebAPI and others) and have custom JsonConverters for reading/writing JSON to the correct "Slide" implementation. Those converters are registered in the global SignalR JsonSerializerSettings:

```
            var settings = new JsonSerializerSettings();

            settings.Converters.Add(new JsonSlideWriter());
            settings.Converters.Add(new JsonSlideReader());

            var serializer = JsonSerializer.Create(settings);
            GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => serializer);
```

But this is ignored by the Microsoft.AspNet.SignalR.Json.JRawValue class which constructs its own JsonSerializerSettings via Microsoft.AspNet.SignalR.Json.JsonUtility.CreateDefaultSerializerSettings():

```
    public static JsonSerializerSettings CreateDefaultSerializerSettings()
    {
      return new JsonSerializerSettings()
      {
        MaxDepth = new int?(20)
      };
    }
```

Please could the JRawValue use the registered JsonSerializerSettings - or allow extensibility/configuration in some other way?

Kind regards,

**Comment by sickboy** [comment]
+1

**Comment by AkosLukacs** [comment]
This kills Nodatime LocalDate deserialization (hey @jskeet ) too.
According to the stackTrace this boils down to this line: https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/Json/JRawValue.cs#L27 

`var serializer = JsonUtility.CreateDefaultSerializer();`

That calls another static class, that creates a new SerializerSettings, and ignores any configuration:
```        
public static JsonSerializerSettings CreateDefaultSerializerSettings()
     {
         return new JsonSerializerSettings() { MaxDepth = DefaultMaxDepth };
     }
```
https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/Json/JsonUtility.cs#L72

I would guess this isn't the most performant thing in the world...

Below is a SignalR stacktrace, the actual value sent from the client is "2016-04-08T22:00:00.000Z", but Newtonsoft's DateParseHandling kicks in, and converts the ISO string to the "friendly" thing seen in the stacktrace

```
{"I":"0","E":"Error converting value 2016. 04. 08. 22:00:00 to type 'NodaTime.LocalDate'. Path '', line 1, position 26.","T":"   
 at: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
 at: Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
 at: Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
 at: Microsoft.AspNet.SignalR.Json.JRawValue.ConvertTo(Type type)
 at: System.Linq.Enumerable.<ZipIterator>d__60`3.MoveNext()
 at: System.Linq.Buffer`1..ctor(IEnumerable`1 source)
 at: System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
 at: Microsoft.AspNet.SignalR.Hubs.HubDispatcher.InvokeHubPipeline(IHub hub, IJsonValue[] parameterValues, MethodDescriptor methodDescriptor, HubRequest hubRequest, StateChangeTracker tracker)"}```

**Comment by IanYates** [comment]
Yep.  We need PR #3343 :)

**Comment by MemeDeveloper** [comment]
:+1: Also having issues with serialization of NodaTime types like @AkosLukacs for hub method parameters - fixed with @BrannonKing 's Resolver - thanks. All of this is way over my head, but seems a little nuts that SignalR docs discuss customizing serialization with JsonSerializerSettings, then just does it's own thing and ignores said customization (at least in some places). Leads slow people like me to a lot of head scratching ;( thanks to @BrannonKing for letting me get on now.

**Comment by Rast1234** [comment]
Still an issue with .net core. Yes i know it's in another repo, just leaving a note here for other wanderers.

**Comment by anurse** [comment]
@Rast1234 Could you file an issue on http://github.com/aspnet/SignalR if you're encountering an issue there? It'll get lost if you report this problem here :).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by MrKWatkins** [comment]
This is still a problem for me.

**Comment by vladar107** [comment]
Still Actual for me

**Comment by WooterTheTroubleshooter** [comment]
Still actual.
